### PR TITLE
Add unmark command

### LINKED ISSUE #69: Mark as not watched
**Is your feature request related to a problem? Please describe.**
When playing a video by mistake, it is mark as watched, even when exiting mpv after a few seconds.

**Describe the solution you'd like**
Add a feature to mark video as not watched

**Additional context**
In TUI, recently watched video can still be listed, with a different markup, to be able to unwatch them.

It can be also a good thing to monitor elapsed time in player, and ask the user if the video should be marked as watched whenever there is not enough elapsed time (half? 80%?).

### PR DESCRIPTION
**Pull request by woefe**
Adds unmark command and more listing options. Fixes #69 

- [x] Add `unmark` command
- [x] Add --order-by option to `list` command
- [x] Change behavior of `--watched` flag and add `--unwatched` flag
- [x] Add unmark behavior to ytccf.sh
- [x] Add database migrations

### CODE REVIEW

**Comment by wavexx** [comment]
Everything seems to work as expected after a brief test both via cli and ytccf (alt-u).
Upgrade worked without issue as well.

**Comment by Glandos** [comment]
Same for me, migration was OK.

Do you plan to add unwatch to TUI also? Or you better support `fzf`?

**Comment by Glandos** [comment]
After more testing, I found that I'm unable to play a video using `ytccf.sh`. I always have: `ERROR: Cannot connect to the database or query failed unexpectedly`. `ytcc tui` seems to work fine.

**Comment by wavexx** [comment]
ytccf works fine here (first thing I tried)

**Comment by woefe** [comment]
Thanks for testing it!

**Comment by woefe** [comment]
@Glandos the ytccf script in your setup is probably using the old command. And I don't plan to add unmark support in the tui. I was actually thinking about removing the tui with the 2.0.0 release. The only reason it's still there is Windows support, because I did not yet write a powershell script.

**Pull request merged**
